# Generated by Django 4.1.2 on 2022-10-27 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteAdmin', '0003_categorytablemodel'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('ImageFile', models.FileField(upload_to='')),
                ('Details', models.CharField(max_length=500)),
                ('Stock', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Category_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteAdmin.categorytablemodel')),
                ('Seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.sellermodel')),
            ],
        ),
    ]
