# Generated by Django 4.1.2 on 2022-10-27 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_productmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='Category_Id',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='Seller_id',
            new_name='Seller',
        ),
    ]
