# Generated by Django 4.1.2 on 2022-10-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=25)),
                ('Address', models.CharField(max_length=500)),
                ('DOB', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=20)),
                ('Username', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
    ]
