# Generated by Django 4.1.2 on 2022-10-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyermodel',
            name='Gender',
            field=models.CharField(max_length=20),
        ),
    ]
