# Generated by Django 4.1.2 on 2022-11-07 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_rename_category_id_productmodel_category_and_more'),
        ('buyer', '0004_remove_cartmodel_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shipping', models.CharField(max_length=255)),
                ('Quantity', models.IntegerField()),
                ('Total_price', models.IntegerField()),
                ('DateTime', models.CharField(max_length=50)),
                ('Status', models.CharField(default='pending', max_length=50)),
                ('Buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.buyermodel')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.productmodel')),
                ('Seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.sellermodel')),
            ],
        ),
    ]
