# Generated by Django 4.1.2 on 2022-11-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0006_cartmodel_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='DateTime',
            new_name='Time',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='Date',
            field=models.CharField(default='10', max_length=50),
        ),
    ]
