# Generated by Django 4.1.2 on 2022-11-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0007_rename_datetime_ordermodel_time_ordermodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='Phone',
            field=models.CharField(default='10', max_length=50),
        ),
    ]
