# Generated by Django 4.1.2 on 2022-10-24 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminmodel',
            old_name='password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='adminmodel',
            old_name='username',
            new_name='Username',
        ),
    ]
